# Generated by Django 5.1.5 on 2025-02-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='signup_method',
            field=models.CharField(choices=[('odontopedia', 'Odontopedia'), ('google', 'GOOGLE')], default='odontopedia', max_length=20),
        ),
    ]
