# Generated by Django 5.1.5 on 2025-02-03 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_signup_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='signup_method',
            new_name='sign_up_method',
        ),
    ]
