# Generated by Django 5.1.5 on 2025-02-10 10:03

import odontopedia.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(default='default_images/profile_image.jpg', upload_to=odontopedia.accounts.models.UploadToUserProfileImage()),
        ),
    ]
