# Generated by Django 5.1.5 on 2025-02-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-02-12 10:00:00'),
            preserve_default=False,
        ),
    ]
