databases:
  - name: odontopedia_db
    plan: free
    databaseName: odontopedia_db
    user: odontopedia_user

services:
  - type: web
    plan: free
    name: odontopedia
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn mysite.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: odontopedia_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4