# Generated by Django 5.1.5 on 2025-02-18 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AvailableSlots',
            new_name='AvailableSlot',
        ),
    ]
