# Generated by Django 5.1.5 on 2025-02-18 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_rename_availableslots_availableslot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetingroom',
            old_name='link',
            new_name='room_link',
        ),
    ]
