# Generated by Django 5.1.5 on 2025-02-19 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_topic_booking_video_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='session_completed',
            field=models.BooleanField(default=False),
        ),
    ]
