# Generated by Django 5.1.5 on 2025-02-20 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_alter_booking_slot'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AvailableSlot',
            new_name='Slot',
        ),
    ]
